def showMenu():
    print("\n===== SISTEMA FINANCEIRO =====")
    print("1 - Adicionar Receita")
    print("2 - Adicionar Despesa")
    print("3 - Listar Transações")
    print("4 - Ver Saldo")
    print("5 - Deletar transação por ID")
    print("6 - Listar apenas receitas")
    print("7 - Gerar relatório geral")
    print("8 - Gerar gráfico financeiro")
    print("0 - Sair")